Adding batch script to archive raindrop bookmark URLs
Presterity/py-script pull request #2
Opened 2017-02-18 02:50 UTC by yakticus

creating batch script that makes sure that raindrop bookmarks are included in the wayback machine (web archive)
    - archive-links.py is the main command-line script that does the archiving
    - raindrop_api.py contains general-purpose APIs for accessing raindrop (extracted from extract-raindrop-bookmarks.py)
    - extract-raindrop-bookmarks.py - refactored to use the above module
    - wayback_api.py - general purpose API for accessing the web archive

TODO:
    - seems to have problems with URLs that have query params (at least this example doesn't work: https://www.nytimes.com/2017/02/17/opinion/a-party-to-the-russian-connection.html?smid=tw-share)
    - make the requests async (should be faster)

2017-02-19 22:27 UTC, jpowerwa requested changes
Looks great overall. A few requested changes:
1. Restore the log pattern in extract-raindrop-bookmarks and repeat in archive-links.
2. Do not pass logger as an argument; declare module-level logger named `log` in raindrop_api.py.
3. Please use 4-space indents instead of 8.
4. Minor typo: `DEFAUlT` -> `DEFAULT`

2017-02-19 22:27 UTC, jpowerwa commented on extract-raindrop-bookmarks.py
> +DEFAUlT_PAGE_SIZE = 40
Typo? I assume you were intending DEFAULT_PAGE_SIZE as the name, in all caps.

2017-02-19 22:27 UTC, jpowerwa commented on archive-links.py
> +
Having log at the module level is actually a Python logging best practice. In non-script modules, you'll often see it declared right after import logging, and set to the logger for `__name__`. That works nicely given the scoped names of Python modules; setting the log level for `foo` also sets it for `foo.*`, `foo.*.*`, etc. I know it seems messy to have it at the module level; it takes some getting used to.

2017-02-19 22:27 UTC, jpowerwa commented on raindrop_api.py
> +
So here, standard Python practice is to do:

```
import logging
log = logging.getLogger(__name__)
```

And then within the module, calls are simply made to `log.debug`, `log.warn`, etc.

2017-02-19 22:27 UTC, jpowerwa commented on raindrop_api.py
> +    if log is not None:
This should go away once the `log` argument is removed, as the logger will be initialized when the module is loaded.

2017-02-19 22:27 UTC, jpowerwa commented on raindrop_api.py
> +    if log is not None:
As above.

2017-02-20 18:18 UTC, yakticus commented
@jpowerwa Thanks for the review, and the pointers in the right direction on logging. I'll get this PR updated sometime tonight.

2017-02-21 03:09 UTC, yakticus commented on extract-raindrop-bookmarks.py
> +DEFAUlT_PAGE_SIZE = 40
yep. thanks.

2017-02-21 03:16 UTC, yakticus commented on archive-links.py
> +
Thanks for filling me in. Globals and module-scoped stuff is a no-no in environments I'm used to. Soon I will learn the ways of Python. :)

2017-02-21 03:41 UTC, yakticus commented
@jpowerwa updated with feedback incorporated.

2017-02-21 04:27 UTC, jpowerwa reviewed
Looks great! Go ahead and merge to master and then delete the branch.

2017-02-21 04:28 UTC, jpowerwa approved these changes

2017-02-21 19:25 UTC, merged